### ISSUE TITLE
Use localStorage instead of cookies

### ISSUE THREAD

**Issue by mirko911** [SheepWizard/COD4-MENU-BUILDER#6]
I think it would be easier, if you use the localStorage instead of cookies.

```
var testObject = { 'one': 1, 'two': 2, 'three': 3 };

// Put the object into storage
localStorage.setItem('testObject', JSON.stringify(testObject));

// Retrieve the object from storage
var retrievedObject = localStorage.getItem('testObject');

console.log('retrievedObject: ', JSON.parse(retrievedObject));
```

I also think, that it would be easier to use json in general. It could save you alot of code

**Comment by SheepWizard** [comment]
Alright i'll look into it, thanks

**Comment by SheepWizard** [comment]
Added, good suggestion 👌 [https://github.com/SheepWizard/COD4-MENU-BUILDER/commit/5ec5a7fc82ec12164b79326377ddd74db9b0628c](url)

Also it probably would of been easier to use JSON, i'll change it as some point

**Comment by mirko911** [comment]
you failed with the commit url 5ec5a7fc82ec12164b79326377ddd74db9b0628c
